name: CI - Build & Test Docker Image

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - nams: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-nginx .

      - name: Run container
        run: docker run -d -p 8080:80 --name test-nginx my-nginx

      - name: Test container with curl
        run: curl -v http://localhost:8080
